<aside class="menu">
  <ul class="menu-list block is-uppercase">
    <li><a class="has-background-light has-text-black" href="/aplicacion/contenido/codigos/componendo.php">De novo codice componendo</a></li>
    <li><a class="has-background-light has-text-black" href="/aplicacion/contenido/codigos/confirmando.php">De Iustiniano codice confirmando</a></li>
    <li><a class="has-background-light has-text-black" href="/aplicacion/contenido/codigos/emendatio.php">De emendatione codicis Iustiniani et secunda eius editione</a></li>
  </ul>
  <div class="grid is-col-min-1 block is-uppercase">
    <div class="cell"><a href="contenido/novelas/1.php" class="button is-light">1</a></div>
    <div class="cell"><a href="contenido/novelas/2.php" class="button is-light">2</a></div>
    <div class="cell"><a href="contenido/novelas/3.php" class="button is-light">3</a></div>
    <div class="cell"><a href="contenido/novelas/4.php" class="button is-light">4</a></div>
    <div class="cell"><a href="contenido/novelas/5.php" class="button is-light">5</a></div>
    <div class="cell"><a href="contenido/novelas/6.php" class="button is-light">6</a></div>
    <div class="cell"><a href="contenido/novelas/7.php" class="button is-light">7</a></div>
    <div class="cell"><a href="contenido/novelas/8.php" class="button is-light">8</a></div>
    <div class="cell"><a href="contenido/novelas/9.php" class="button is-light">9</a></div>
    <div class="cell"><a href="contenido/novelas/10.php" class="button is-light">10</a></div>
    <div class="cell"><a href="contenido/novelas/11.php" class="button is-light">11</a></div>
    <div class="cell"><a href="contenido/novelas/12.php" class="button is-light">12</a></div>
    <div class="cell"><a href="contenido/novelas/13.php" class="button is-light">13</a></div>
    <div class="cell"><a href="contenido/novelas/14.php" class="button is-light">14</a></div>
    <div class="cell"><a href="contenido/novelas/15.php" class="button is-light">15</a></div>
    <div class="cell"><a href="contenido/novelas/16.php" class="button is-light">16</a></div>
    <div class="cell"><a href="contenido/novelas/17.php" class="button is-light">17</a></div>
    <div class="cell"><a href="contenido/novelas/18.php" class="button is-light">18</a></div>
    <div class="cell"><a href="contenido/novelas/19.php" class="button is-light">19</a></div>
    <div class="cell"><a href="contenido/novelas/20.php" class="button is-light">20</a></div>
    <div class="cell"><a href="contenido/novelas/21.php" class="button is-light">21</a></div>
    <div class="cell"><a href="contenido/novelas/22.php" class="button is-light">22</a></div>
    <div class="cell"><a href="contenido/novelas/23.php" class="button is-light">23</a></div>
    <div class="cell"><a href="contenido/novelas/24.php" class="button is-light">24</a></div>
    <div class="cell"><a href="contenido/novelas/25.php" class="button is-light">25</a></div>
    <div class="cell"><a href="contenido/novelas/26.php" class="button is-light">26</a></div>
    <div class="cell"><a href="contenido/novelas/27.php" class="button is-light">27</a></div>
    <div class="cell"><a href="contenido/novelas/28.php" class="button is-light">28</a></div>
    <div class="cell"><a href="contenido/novelas/29.php" class="button is-light">29</a></div>
    <div class="cell"><a href="contenido/novelas/30.php" class="button is-light">30</a></div>
    <div class="cell"><a href="contenido/novelas/31.php" class="button is-light">31</a></div>
    <div class="cell"><a href="contenido/novelas/32.php" class="button is-light">32</a></div>
    <div class="cell"><a href="contenido/novelas/33.php" class="button is-light">33</a></div>
    <div class="cell"><a href="contenido/novelas/34.php" class="button is-light">34</a></div>
    <div class="cell"><a href="contenido/novelas/35.php" class="button is-light">35</a></div>
    <div class="cell"><a href="contenido/novelas/36.php" class="button is-light">36</a></div>
    <div class="cell"><a href="contenido/novelas/37.php" class="button is-light">37</a></div>
    <div class="cell"><a href="contenido/novelas/38.php" class="button is-light">38</a></div>
    <div class="cell"><a href="contenido/novelas/39.php" class="button is-light">39</a></div>
    <div class="cell"><a href="contenido/novelas/40.php" class="button is-light">40</a></div>
    <div class="cell"><a href="contenido/novelas/41.php" class="button is-light">41</a></div>
    <div class="cell"><a href="contenido/novelas/42.php" class="button is-light">42</a></div>
    <div class="cell"><a href="contenido/novelas/43.php" class="button is-light">43</a></div>
    <div class="cell"><a href="contenido/novelas/44.php" class="button is-light">44</a></div>
    <div class="cell"><a href="contenido/novelas/45.php" class="button is-light">45</a></div>
    <div class="cell"><a href="contenido/novelas/46.php" class="button is-light">46</a></div>
    <div class="cell"><a href="contenido/novelas/47.php" class="button is-light">47</a></div>
    <div class="cell"><a href="contenido/novelas/48.php" class="button is-light">48</a></div>
    <div class="cell"><a href="contenido/novelas/49.php" class="button is-light">49</a></div>
    <div class="cell"><a href="contenido/novelas/50.php" class="button is-light">50</a></div>
    <div class="cell"><a href="contenido/novelas/51.php" class="button is-light">51</a></div>
    <div class="cell"><a href="contenido/novelas/52.php" class="button is-light">52</a></div>
    <div class="cell"><a href="contenido/novelas/53.php" class="button is-light">53</a></div>
    <div class="cell"><a href="contenido/novelas/54.php" class="button is-light">54</a></div>
    <div class="cell"><a href="contenido/novelas/55.php" class="button is-light">55</a></div>
    <div class="cell"><a href="contenido/novelas/56.php" class="button is-light">56</a></div>
    <div class="cell"><a href="contenido/novelas/57.php" class="button is-light">57</a></div>
    <div class="cell"><a href="contenido/novelas/58.php" class="button is-light">58</a></div>
    <div class="cell"><a href="contenido/novelas/59.php" class="button is-light">59</a></div>
    <div class="cell"><a href="contenido/novelas/60.php" class="button is-light">60</a></div>
    <div class="cell"><a href="contenido/novelas/61.php" class="button is-light">61</a></div>
    <div class="cell"><a href="contenido/novelas/62.php" class="button is-light">62</a></div>
    <div class="cell"><a href="contenido/novelas/63.php" class="button is-light">63</a></div>
    <div class="cell"><a href="contenido/novelas/64.php" class="button is-light">64</a></div>
    <div class="cell"><a href="contenido/novelas/65.php" class="button is-light">65</a></div>
    <div class="cell"><a href="contenido/novelas/66.php" class="button is-light">66</a></div>
    <div class="cell"><a href="contenido/novelas/67.php" class="button is-light">67</a></div>
    <div class="cell"><a href="contenido/novelas/68.php" class="button is-light">68</a></div>
    <div class="cell"><a href="contenido/novelas/69.php" class="button is-light">69</a></div>
    <div class="cell"><a href="contenido/novelas/70.php" class="button is-light">70</a></div>
    <div class="cell"><a href="contenido/novelas/71.php" class="button is-light">71</a></div>
    <div class="cell"><a href="contenido/novelas/72.php" class="button is-light">72</a></div>
    <div class="cell"><a href="contenido/novelas/73.php" class="button is-light">73</a></div>
    <div class="cell"><a href="contenido/novelas/74.php" class="button is-light">74</a></div>
    <div class="cell"><a href="contenido/novelas/75.php" class="button is-light">75</a></div>
    <div class="cell"><a href="contenido/novelas/76.php" class="button is-light">76</a></div>
    <div class="cell"><a href="contenido/novelas/77.php" class="button is-light">77</a></div>
    <div class="cell"><a href="contenido/novelas/78.php" class="button is-light">78</a></div>
    <div class="cell"><a href="contenido/novelas/79.php" class="button is-light">79</a></div>
    <div class="cell"><a href="contenido/novelas/80.php" class="button is-light">80</a></div>
    <div class="cell"><a href="contenido/novelas/81.php" class="button is-light">81</a></div>
    <div class="cell"><a href="contenido/novelas/82.php" class="button is-light">82</a></div>
    <div class="cell"><a href="contenido/novelas/83.php" class="button is-light">83</a></div>
    <div class="cell"><a href="contenido/novelas/84.php" class="button is-light">84</a></div>
    <div class="cell"><a href="contenido/novelas/85.php" class="button is-light">85</a></div>
    <div class="cell"><a href="contenido/novelas/86.php" class="button is-light">86</a></div>
    <div class="cell"><a href="contenido/novelas/87.php" class="button is-light">87</a></div>
    <div class="cell"><a href="contenido/novelas/88.php" class="button is-light">88</a></div>
    <div class="cell"><a href="contenido/novelas/89.php" class="button is-light">89</a></div>
    <div class="cell"><a href="contenido/novelas/90.php" class="button is-light">90</a></div>
    <div class="cell"><a href="contenido/novelas/91.php" class="button is-light">91</a></div>
    <div class="cell"><a href="contenido/novelas/92.php" class="button is-light">92</a></div>
    <div class="cell"><a href="contenido/novelas/93.php" class="button is-light">93</a></div>
    <div class="cell"><a href="contenido/novelas/94.php" class="button is-light">94</a></div>
    <div class="cell"><a href="contenido/novelas/95.php" class="button is-light">95</a></div>
    <div class="cell"><a href="contenido/novelas/96.php" class="button is-light">96</a></div>
    <div class="cell"><a href="contenido/novelas/97.php" class="button is-light">97</a></div>
    <div class="cell"><a href="contenido/novelas/98.php" class="button is-light">98</a></div>
    <div class="cell"><a href="contenido/novelas/99.php" class="button is-light">99</a></div>
    <div class="cell"><a href="contenido/novelas/100.php" class="button is-light">100</a></div>
    <div class="cell"><a href="contenido/novelas/101.php" class="button is-light">101</a></div>
    <div class="cell"><a href="contenido/novelas/102.php" class="button is-light">102</a></div>
    <div class="cell"><a href="contenido/novelas/103.php" class="button is-light">103</a></div>
    <div class="cell"><a href="contenido/novelas/104.php" class="button is-light">104</a></div>
    <div class="cell"><a href="contenido/novelas/105.php" class="button is-light">105</a></div>
    <div class="cell"><a href="contenido/novelas/106.php" class="button is-light">106</a></div>
    <div class="cell"><a href="contenido/novelas/107.php" class="button is-light">107</a></div>
    <div class="cell"><a href="contenido/novelas/108.php" class="button is-light">108</a></div>
    <div class="cell"><a href="contenido/novelas/109.php" class="button is-light">109</a></div>
    <div class="cell"><a href="contenido/novelas/110.php" class="button is-light">110</a></div>
    <div class="cell"><a href="contenido/novelas/111.php" class="button is-light">111</a></div>
    <div class="cell"><a href="contenido/novelas/112.php" class="button is-light">112</a></div>
    <div class="cell"><a href="contenido/novelas/113.php" class="button is-light">113</a></div>
    <div class="cell"><a href="contenido/novelas/114.php" class="button is-light">114</a></div>
    <div class="cell"><a href="contenido/novelas/115.php" class="button is-light">115</a></div>
    <div class="cell"><a href="contenido/novelas/116.php" class="button is-light">116</a></div>
    <div class="cell"><a href="contenido/novelas/117.php" class="button is-light">117</a></div>
    <div class="cell"><a href="contenido/novelas/118.php" class="button is-light">118</a></div>
    <div class="cell"><a href="contenido/novelas/119.php" class="button is-light">119</a></div>
    <div class="cell"><a href="contenido/novelas/120.php" class="button is-light">120</a></div>
    <div class="cell"><a href="contenido/novelas/121.php" class="button is-light">121</a></div>
    <div class="cell"><a href="contenido/novelas/122.php" class="button is-light">122</a></div>
    <div class="cell"><a href="contenido/novelas/123.php" class="button is-light">123</a></div>
    <div class="cell"><a href="contenido/novelas/124.php" class="button is-light">124</a></div>
    <div class="cell"><a href="contenido/novelas/125.php" class="button is-light">125</a></div>
    <div class="cell"><a href="contenido/novelas/126.php" class="button is-light">126</a></div>
    <div class="cell"><a href="contenido/novelas/127.php" class="button is-light">127</a></div>
    <div class="cell"><a href="contenido/novelas/128.php" class="button is-light">128</a></div>
    <div class="cell"><a href="contenido/novelas/129.php" class="button is-light">129</a></div>
    <div class="cell"><a href="contenido/novelas/130.php" class="button is-light">130</a></div>
    <div class="cell"><a href="contenido/novelas/131.php" class="button is-light">131</a></div>
    <div class="cell"><a href="contenido/novelas/132.php" class="button is-light">132</a></div>
    <div class="cell"><a href="contenido/novelas/133.php" class="button is-light">133</a></div>
    <div class="cell"><a href="contenido/novelas/134.php" class="button is-light">134</a></div>
    <div class="cell"><a href="contenido/novelas/135.php" class="button is-light">135</a></div>
    <div class="cell"><a href="contenido/novelas/136.php" class="button is-light">136</a></div>
    <div class="cell"><a href="contenido/novelas/137.php" class="button is-light">137</a></div>
    <div class="cell"><a href="contenido/novelas/138.php" class="button is-light">138</a></div>
    <div class="cell"><a href="contenido/novelas/139.php" class="button is-light">139</a></div>
    <div class="cell"><a href="contenido/novelas/140.php" class="button is-light">140</a></div>
    <div class="cell"><a href="contenido/novelas/141.php" class="button is-light">141</a></div>
    <div class="cell"><a href="contenido/novelas/142.php" class="button is-light">142</a></div>
    <div class="cell"><a href="contenido/novelas/143.php" class="button is-light">143</a></div>
    <div class="cell"><a href="contenido/novelas/144.php" class="button is-light">144</a></div>
    <div class="cell"><a href="contenido/novelas/145.php" class="button is-light">145</a></div>
    <div class="cell"><a href="contenido/novelas/146.php" class="button is-light">146</a></div>
    <div class="cell"><a href="contenido/novelas/147.php" class="button is-light">147</a></div>
    <div class="cell"><a href="contenido/novelas/148.php" class="button is-light">148</a></div>
    <div class="cell"><a href="contenido/novelas/149.php" class="button is-light">149</a></div>
    <div class="cell"><a href="contenido/novelas/150.php" class="button is-light">150</a></div>
    <div class="cell"><a href="contenido/novelas/151.php" class="button is-light">151</a></div>
    <div class="cell"><a href="contenido/novelas/152.php" class="button is-light">152</a></div>
    <div class="cell"><a href="contenido/novelas/153.php" class="button is-light">153</a></div>
    <div class="cell"><a href="contenido/novelas/154.php" class="button is-light">154</a></div>
    <div class="cell"><a href="contenido/novelas/155.php" class="button is-light">155</a></div>
    <div class="cell"><a href="contenido/novelas/156.php" class="button is-light">156</a></div>
    <div class="cell"><a href="contenido/novelas/157.php" class="button is-light">157</a></div>
    <div class="cell"><a href="contenido/novelas/158.php" class="button is-light">158</a></div>
    <div class="cell"><a href="contenido/novelas/159.php" class="button is-light">159</a></div>
    <div class="cell"><a href="contenido/novelas/160.php" class="button is-light">160</a></div>
    <div class="cell"><a href="contenido/novelas/161.php" class="button is-light">161</a></div>
    <div class="cell"><a href="contenido/novelas/162.php" class="button is-light">162</a></div>
    <div class="cell"><a href="contenido/novelas/163.php" class="button is-light">163</a></div>
    <div class="cell"><a href="contenido/novelas/164.php" class="button is-light">164</a></div>
    <div class="cell"><a href="contenido/novelas/165.php" class="button is-light">165</a></div>
    <div class="cell"><a href="contenido/novelas/166.php" class="button is-light">166</a></div>
    <div class="cell"><a href="contenido/novelas/167.php" class="button is-light">167</a></div>
    <div class="cell"><a href="contenido/novelas/168.php" class="button is-light">168</a></div>
  </div>
  <p>Iustiniani XIII Edicta quae vocantur</p>
  <div class="grid is-col-min-1 block is-uppercase">
    <div class="cell"><a href="contenido/novelas/1.php" class="button is-light">1</a></div>
    <div class="cell"><a href="contenido/novelas/2.php" class="button is-light">2</a></div>
    <div class="cell"><a href="contenido/novelas/3.php" class="button is-light">3</a></div>
    <div class="cell"><a href="contenido/novelas/4.php" class="button is-light">4</a></div>
    <div class="cell"><a href="contenido/novelas/5.php" class="button is-light">5</a></div>
    <div class="cell"><a href="contenido/novelas/6.php" class="button is-light">6</a></div>
    <div class="cell"><a href="contenido/novelas/7.php" class="button is-light">7</a></div>
    <div class="cell"><a href="contenido/novelas/8.php" class="button is-light">8</a></div>
    <div class="cell"><a href="contenido/novelas/9.php" class="button is-light">9</a></div>
    <div class="cell"><a href="contenido/novelas/1.php" class="button is-light">10</a></div>
    <div class="cell"><a href="contenido/novelas/1.php" class="button is-light">11</a></div>
    <div class="cell"><a href="contenido/novelas/1.php" class="button is-light">12</a></div>
    <div class="cell"><a href="contenido/novelas/1.php" class="button is-light">13</a></div>
  </div>
  <p>Apéndice constitución dispersarum</p>
  <div class="grid is-col-min-1 block is-uppercase">
    <div class="cell"><a href="contenido/novelas/1.php" class="button is-light">1</a></div>
    <div class="cell"><a href="contenido/novelas/2.php" class="button is-light">2</a></div>
    <div class="cell"><a href="contenido/novelas/3.php" class="button is-light">3</a></div>
    <div class="cell"><a href="contenido/novelas/4.php" class="button is-light">4</a></div>
    <div class="cell"><a href="contenido/novelas/5.php" class="button is-light">5</a></div>
    <div class="cell"><a href="contenido/novelas/6.php" class="button is-light">6</a></div>
    <div class="cell"><a href="contenido/novelas/7.php" class="button is-light">7</a></div>
    <div class="cell"><a href="contenido/novelas/8.php" class="button is-light">8</a></div>
    <div class="cell"><a href="contenido/novelas/9.php" class="button is-light">9</a></div>
  </div>
  <p>Iuliani Epitome Latina Novellarum Iustiniani (Hänel)</p>
  <p><a href="#">1-80</a> - <a href="#">81-124</a></p>
</aside class="menu">